#!/usr/bin/env bash

bake_require github.com/kyleburton/bake-recipies/emacs/cider.sh

bake_task run_emacs "Run emacs with Kyle's configuration"
function run_emacs () {
  emacs -nw -q -l $HOME/.bake/packages/github.com/kyleburton/bake-recipies/files/emacs/.emacs "$@"
}

bake_task get-sample-data "Download some sample data..."
function get-sample-data () {
  local url="http://free-email-database.blogspot.com/2008/12/welcome-to-free-e-mail-database.html"
  test -d data || mkdir data
  for ii in $(seq 5); do
    test -f data/$ii.html || curl "$url" > data/$ii.html
  done
  # TODO: download & extract the census names file
  test -e "dist.female.first.txt" && mv "dist.female.first.txt"  "dist.female.first"
  test -e "dist.male.first.txt"   && mv "dist.male.first.txt"    "dist.male.first"
  test -e "dist.all.last.txt"     && mv "dist.all.last.txt"      "dist.all.last"

  # TODO: download & extract the npa-nxx data file
  if [ ! -e "data/allutlzd.txt" ]; then
      (
      cd data
      unzip allutlzd.zip
      )
  fi
}

bake_task run_dev "Run the project's main (the NREPL server)"
function run_dev () {
  lein run
}

bake_task extract-emails "Extract list of email addresses from the HTML files"
function extract-emails () {
  get-sample-data
  time lein run  -m data-talk.data extract-emails
}

bake_task gen-rand-email-file "Generate a random list of emails."
function gen-rand-email-file () {
  time lein run  -m data-talk.data generate-email-address-file
}

bake_task gen-rand-phones-file "Generate a random list of phones."
function gen-rand-phones-file () {
  time lein run  -m data-talk.data generate-phones-file
}


bake_task generate-data "Generate all the example data files"
function generate-data () {
  extract-emails
  gen-rand-email-file
  gen-rand-phones-file
}
